use_frameworks!

target 'TestMixAndMatch_Example' do
  pod 'TestMixAndMatch', :path => '../'

  target 'TestMixAndMatch_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
